name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  nightly-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npm test
        env:
          CI: true

      - name: Display summary reports
        run: |
          echo "### Available performance summary reports"
          if [ -d performance-reports ]; then
            for file in performance-reports/*.txt; do
              echo "**$(basename $file)**";
              head -n 20 "$file" || true;
              echo "..."
            done
          else
            echo "No performance-reports directory found"
          fi

      - name: Upload performance report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: performance.md
          retention-days: 30

      - name: Commit updated performance report
        if: github.event_name != 'pull_request' && always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add performance.md
          git commit -m "Update performance report [skip ci]" || echo "No changes to commit"
          git push
